name: "build and deploy"

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "14.x"
      - run: yarn
      - name: push docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luissaybe/prerender-puppeteer
          tags: latest